language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - nightly

before_script: 
  - composer install
  - npm run build
  - cp .env.example .env
  - php artisan key:generate -f
  - php artisan migrate -f

script: vendor/bin/phpunit --configuration phpunit.xml